### PR TITLE
WIP: update to ECOS 2.0.2

### PR DESCRIPTION
**Pull request by mlubin**
Just an update to the new API, but doesn't expose exponential cones (#24) or branch & bound (#16). That can be added separately once we bump the binaries.
Seems to pass JuMP and Convex.jl tests locally, let's see what travis says on linux.
CC @tkelman @madeleineudell @adomahidi

### CODE REVIEW

**Comment by mlubin** [comment]
Also CC @IainNZ to test if the new version fixes the issue with incorrect answers

**Comment by mlubin** [comment]
Passing on linux.
@tkelman, are the windows issues resolved at this point such that we can pack up a working binary?

**Comment by tkelman** [comment]
Yeah, I think so, but I'll double-check. Mind if I push bindeps adjustments to this branch if everything looks good?

For some future version we may want to move from `Clong` to `Int`, but that should probably not be necessary just yet.

**Comment by mlubin** [comment]
> Mind if I push bindeps adjustments to this branch if everything looks good?

Sure, thanks!

**Comment by tkelman** [comment]
Done. Anything needed for the homebrew update other than the version number and source checksum?

**Comment by mlubin** [comment]
Nope, I think that's it if it works. Once homebrew is bumped we're forced to merge this and tag, but that's okay.

**Comment by tkelman** [comment]
Sure would be nice if the most popular mac package manager allowed you to depend on previous versions of things in a more sane way than copying the build instructions to a new name...

**Comment by tkelman** [comment]
restarted the osx builds, let's see what happens

**Comment by mlubin** [comment]
Passing!

**Comment by mlubin** [comment]
@tkelman, win64 segfault on the merge commit: https://ci.appveyor.com/project/mlubin/ecos-jl/build/1.0.66/job/fgi82sd007dorcgy#L90

**Comment by tkelman** [comment]
Ick. Intermittent failures are the worst. Will see if I can reproduce locally.

**Pull request merged**
