### PR TITLE
Add test for an infeasible problem

### PR DESCRIPTION
**Pull request by IainNZ**
Currently fails on ECOS 1.0.5.

It looks like in #16 that we can't upgrade, is that correct?

Not sure if its been fixed, I'm going to file an issue to see whats up.

### CODE REVIEW

**Comment by IainNZ** [comment]
https://github.com/embotech/ecos/issues/109

**Comment by tkelman** [comment]
> It looks like in #16 that we can't upgrade, is that correct?

Not until the win64 version builds and passes its tests without segfaulting.

**Comment by IainNZ** [comment]
For recording's sake, here is the test in JuMP format:
```
using JuMP
 import ECOS

 m = Model(solver=ECOS.ECOSSolver(verbose=true))
 @defVar(m, x)
 @defVar(m, u <= 0)
 @defVar(m, v >= 0)
 @setObjective(m, Max, x)
 @addConstraint(m, x == 3)
 @addConstraint(m, 8u + 9v <= 25)
 @addConstraint(m, u + v - x == 0)
 solve(m)

 println(m)
```

**Comment by IainNZ** [comment]
Problem is confirmed to be in ECOS

**Comment by tkelman** [comment]
worth a rebase?

**Comment by IainNZ** [comment]
mmm looking at it now

**Pull request merged**
