### PR TITLE
fix #19, use mirroring url for windows binary

### LINKED ISSUE #19: Use mirroring url to make downloads more robust
This is a reminder to myself, if no one beats me to it, that sourceforge is awful and we should try to use the S3 caching for binary downloads that we use in base Julia to make things more reliable.

### PR DESCRIPTION
**Pull request by tkelman**

### CODE REVIEW

**Comment by mlubin** [comment]
```
LoadError: I don't know how to unpack C:\Users\appveyor\.julia\v0.4\ECOS\deps\downloads\download
while loading C:\Users\appveyor\.julia\v0.4\ECOS\deps\build.jl, in expression starting on line 49 
```

**Comment by tkelman** [comment]
Yeah, damn, https://ci.appveyor.com/project/mlubin/ecos-jl/build/1.0.43/job/9c726yr2c31ag7dw

@staticfloat little help?

**Comment by staticfloat** [comment]
Looks like the filename isn't getting set properly on download, so `BinDeps` doesn't know what to do with it?  Also, I just did this, which is quite helpful in figuring out what's going on:

```
$  curl 'https://cache.e.ip.saba.us/http://sourceforge.net/projects/juliadeps-win/files/ecos-e05a605588c38ad72e843f36af17f8f84e4e2ccb.7z/download' -L -v -O /dev/null
* Hostname was NOT found in DNS cache

<snip>
... blah blah blah ...
</snip>

< HTTP/1.1 302 FOUND
< Location: http://sourceforge.net/projects/juliadeps-win/files/ecos-e05a605588c38ad72e843f36af17f8f84e4e2ccb.7z/download
<snip>
... blah blah blah ...
</snip>

* Connected to downloads.sourceforge.net (216.34.181.59) port 80 (#2)
> GET /project/juliadeps-win/ecos-e05a605588c38ad72e843f36af17f8f84e4e2ccb.7z?
< HTTP/1.1 200 OK

<snip>
... blah blah blah ...
</snip>
```

I've snipped out everything but the most important bits, which are that the cache server gave me a `302`.  This means that whatever you tried to do on appveyor didn't send the right request URL to trigger caching.   It's cached now, so subsequent calls should work, yielding `301`'s instead of `302`'s from the caching server:

```
$ curl 'https://cache.e.ip.saba.us/http://sourceforge.net/projects/juliadeps-win/files/ecos-e05a605588c38ad72e843f36af17f8f84e4e2ccb.7z/download' -L -v -O /dev/null
< HTTP/1.1 301 MOVED PERMANENTLY
<snip>
... blah blah blah ...
</snip>

Connected to juliacache.s3.amazonaws.com (54.231.34.65) port 443 (#1)
GET /ecos-e05a605588c38ad72e843f36af17f8f84e4e2ccb.7z HTTP/1.1
< HTTP/1.1 200 OK
```

Now, this isn't the actual issue, although it should be addressed.  The actual issue is that [BinDeps takes the `basename()` of whatever you give it](https://github.com/JuliaLang/BinDeps.jl/blob/master/src/dependencies.jl#L333) as the local filename.  I looked into the best way to solve this, and it turns out I've been giving sourceforge a bad rap all this time in my code comments because I thought you had to append `/download` to a filename to actually get it, but it looks like you don't need to do that!  So the caching server now supports omitting `/download` (indeed, I'd prefer it if we moved away from using the `/download` extension as much as possible) so that BinDeps doesn't get confused, and then knows how to extract the `.7z` file.

**Comment by tkelman** [comment]
Thank you kindly, as always. Let's see if dropping /download does the trick.

**Comment by mlubin** [comment]
All green now

**Pull request merged**
